version: "3"
services:
  movies-service-db:
    image: postgres
    environment:
      POSTGRES_DB: movies
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  movies-service:
    build: ./movies-service
    command: npm start
    ports:
      - "8081:8081"
    volumes:
      - ./movies-service:/cinema-api/movies-service
    depends_on:
      - movies-service-db